### PR TITLE
Add checks and error messages for CMSSW, SAMADhi

### PR DESCRIPTION
**Pull request by pieterdavid**
fixes https://github.com/cp3-llbb/CommonTools/issues/10

### CODE REVIEW

**Comment by swertz** [comment]
Thanks! Maybe we could do the same in `condorTools`?

**Comment by pieterdavid** [comment]
Good idea... then we may was well try to put it all together to avoid having hard-coded paths in two places - this is what I tried with above commit (a bit double work, because with createSampleJson.py it will simply fail to find `cp3_llbb.CommonTools.samadhi_imports`, but still more descriptive than `KeyError: CMSSW_BASE` - with the system python (2.6.6 still) `import condorTools` gives a syntax error at a dict comprehension for now)

**Comment by pieterdavid** [comment]
One more thing: I also changed the hard-coded python path in the first line by `/usr/bin/env python`, because that failed with "canot load shared library libpython2..."

**Comment by swertz** [comment]
Thanks!

**Pull request merged**
