### PR TITLE
Add helper functions to combine scale-factors

### PR DESCRIPTION
**Pull request by blinkseb**
A function `common::combineScaleFactors<>()` is available globally
for both `histFactory` and `treeFactory`.

Two signatures are available:
  - The first one takes an array of scale-factors, and the wanted
  variation, and return the combination of the scale-factors.
  - The second one is similar, but accepts also a correlation matrix
  between the different scale-factors.

The template is just the number of scale-factors to consider. The
algorithm is generic enough to deal with an arbitrary number.

For signature #1, non-correlated scale-factors are considered.

This function is only valid if the combination of scale-factors is a
simple product of the terms.

The algorithm implemented is the standard uncertainty propagation formula, taking into account correlations between parameters:
ql_36e3ee8a88f84f2067cca916ec66c529_l3

Rho is the correlation matrix.

In our case, `f` is defined by a product of all the variables, so the formula simplifies to:
ql_5a1e1b5f9e009bc92eccc0150c86d471_l3

which is what is implemented.

### How-to use

Thanks to `C++11`, it's possible to call these new function inline, without having to declare variables. An example of such call is:

```C++
float weight = common::combineScaleFactors<2>({{{ 1, 0.05 }, { 0.9, 0.032 }}}, common::Variation::UP);
```

The template argument is simply the number of scale-factors in the list (2 in this case). The first argument is a list of scale-factors. A scale-factor is defined by a `pair` of float, where the first value is the nominal scale-factor, and the second the absolute error on this value. Such a pair can be defined on the fly by the syntax `{SF, error}`. To create a list of scale-factor, simply create a list of pair and wrap them with **two** `{` / `}` (this is a limitation of C++11 and no longer required with C++14). So in the example above, it's a list of two scale-factors, 1 +- 0.05 and 0.9 +- 0.032.

Second argument ask for the up variation, so the function will return `f + Δf`. You can also ask for nominal (`f`) or down (`f - Δf`).

#### Correlations

The above example suppose uncorrelated scale-factors. If you want to add correlations, you can use the following syntax:

```C++
float weight = common::combineScaleFactors<2>({{{ 1, 0.05 }, { 0.9, 0.032 }}}, {{1, 1}, {1, 1}}, common::Variation::UP);
```

Notice the second argument is different and is now the correlation matrix. No checks are performed to see if the correlation matrix is symmetric and correct, so be careful. Also note that in this case, only one pair of `{}` is necessary for defining the matrix.

The matrix definition syntax is: `{<row 1>, <row 2>, <row 3>, ...}`, where `<row>` is defined by `{col1, col2, col3, ...`}

### CODE REVIEW

**Comment by OlivierBondu** [comment]
sounds nice !

I added a 'validation needed' tag given it's somewhat a central and critical complex thing... Could someone test ?

**Comment by blinkseb** [comment]
There's also some unit-tests of the code in `common/tests/` which check some basic combination against some calculation. But I agree I tested only some trivial cases, and it's possible I used the wrong formula everywhere :smile:

**Comment by blinkseb** [comment]
It seems like the parser does not recognize the branches inside the function call, so branches are missing on the resulting code (Alex has some issues). I'll investigate, so do not merge label.

**Comment by blinkseb** [comment]
I've just pushed a fix to the parser, everything should works now :)

**Pull request merged**
