### PR TITLE
Link plotter & skimmer to external libraries

### PR DESCRIPTION
**Pull request by swertz**
This will be useful when running MoMEMta, or a matrix-element based event reweighting.

I have NOT yet tested it, but make it available for review or pulling in case someone would already like to try using it ( @BrieucF for MoMEMta maybe?).

### CODE REVIEW

**Comment by BrieucF** [comment]
+1 
Great! I will test it as soon as I have a running MoMEMta configuration!

**Comment by BrieucF** [comment]
We have tested this PR with @blinkseb last week but had problems with missing include in the created CMakeList. Trying to launch momemta jobs, the only way to make it work was to hack the CMakeList on the flight adding e.g. ```include_directories(/home/fynu/bfrancois/scratch/framework/MIS_prod_data/CMSSW_7_6_5/src/cp3_llbb/MoMEMta/build/install/include)``` Seb, do you remember more explicitly what was the issue?

**Comment by blinkseb** [comment]
Yes, but it's not directly related to this PR. The issue is that when using the `includes` command, the code tries to find if the header exists or not by looking if it's an absolute path or not. This fails when using `momemta/ConfigurationReader.h` for example, which is interpreted as a relative path.

The solution IMO is to split `includes` and likes into `include_path` and `headers` or whatever. One specifies a list of path to be added to the cmake file, the other a list of headers to `#include`. Same thing for the libraries?

**Comment by swertz** [comment]
Ok, will have a look!

**Pull request closed without merging**
