### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by blinkseb**
Some improvements, see commits for more details.

### CODE REVIEW

**Comment by blinkseb** [comment]
It seems to crash with root 6.04, investigating

**Comment by blinkseb** [comment]
I tested with a self-compiled root v6.05 and everything works fine. I suspect a bug inside root, maybe fixed?

**Comment by OlivierBondu** [comment]
so should we ask to have v6.05 installed on ingrid then ?

**Comment by blinkseb** [comment]
Not sure for the moment, it's not ready for production. I just need to find some time to test on 6.02 to see if it's working or not.

**Comment by OlivierBondu** [comment]
It does, submitting the PR shortly

**Comment by blinkseb** [comment]
Be careful, it was crashing only when running on more than sample and one plot per sample.

**Comment by OlivierBondu** [comment]
2 samples and 2 plots, still seem to work :smile:

**Comment by blinkseb** [comment]
Great :smile_cat:

**Pull request merged**
