### PR TITLE
Small helper script to plot JSON SFs from framework

### PR DESCRIPTION
**Pull request by blinkseb**
This script will automatically generates 3 plots from a given JSON file:
 - A 2D plot of the SFs or efficiencies vs pt and eta
 - A plot SFs vs pt
 - A plot SFs vs eta

Usage

```bash
./plotFrameworkJSON.py ../../Framework/data/ScaleFactors/Electron_CutBasedID_LooseWP.json Electron_CutBasedID_LooseWP
```

### CODE REVIEW

**Comment by BrieucF** [comment]
Nice! Thanks!

**Comment by BrieucF** [comment]
Works fine. Here is a test for the trigger leg Ele 12. I am surprised to see so big errors (also for high pt bins such as 80 GeV) but looking at the source file it seems coherent. Thanks again!

ele12_trigeff

**Comment by BrieucF** [comment]
For a given pt bin, the error should still be smaller then any of the values in the different eta bin. @blinkseb is investigating.

**Comment by blinkseb** [comment]
Ok it should be fixed, there was an error in the error computation (:smile:)

test_pt

**Pull request merged**
