### PR TITLE
Include user code in the plotter itself

### PR DESCRIPTION
**Pull request by swertz**
Add the possibility to insert user code in the plotter: before, inside, and after the loop over the events (e.g. to define variables used in the histograms, or load information from files, ...). 

This code is defined in the python configuration through the 3 **strings** "code_before_loop", "code_in_loop" and "code_after_loop". Of course, nothing prevents the user to retrieve this code from external files in the python code itself, if defining strings is impractical.

Also, slightly change the way C++ header files are included in the plotter (variable "includes" in the python file): if a headers contains a "<", ie is a library header (e.g. "<TH2.h>" instead of just "TH2.h"), no attempt is made to check the path to the header.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
Sorry I may not have followed the discussion, but what would be an example use-case ?

**Comment by swertz** [comment]
I'm using it for the TTbar system reconstruction, where I need to instanciate a class before the loop, and do some work in the event loop to construct an object which is then called to fill the histograms.

But you might want to use it, for instance, if you want to include new scale factors withouth re-running the whole production: just add some code which loads the file in the plotter.

**Comment by OlivierBondu** [comment]
ah, nice indeed ! :+1:

**Comment by OlivierBondu** [comment]
on second thought, concerning re-running: in HH we use directly the histos to feed combine, so if the SF changes now at plotter level instead of histos, it means we would have to redo the same at the time of datacard/workspace creation...

So in principle it means code duplication so I am not 100% for it... but it's true it makes life much easier for the plots. Couldn't it be a bit more factorized than in the plotter itself, so that it could be called from the StatAnalysis packages as well ?

**Comment by swertz** [comment]
I'm sorry I'm not sure I understand... Since this is histFactory, the new scale factors would be included in your histograms, right?

Besides, nothing prevents you from storing this information in a more "factorised" way (in HHTools or HHStats repo), and retrieve it in histFactory by fetching the needed files when you create your histogram-filler using createPlotter?

**Comment by OlivierBondu** [comment]
ah sorry, I misread then, I have seen 'plotter.cc' and wrongly assumed too quickly we were in plotIt... my bad, apologies for the noise.

So in fact Brieuc can probably confirm, but this PR would then just be a cleaner way of doing what we already do :smile: !

**Comment by BrieucF** [comment]
This is indeed a nice functionality! Thanks! @OlivierBondu I don't plan to change what we are doing now. The point of this PR, I guess, is to provide more flexibility if you need to compute stuff "on the flight" which is not easy now since we are writing the c++ code from python scripts.

**Comment by swertz** [comment]
Actually please wait a bit before merging, I'd like to add something so that the user code can access branches that are not used by any plot (which is currently not possible).

**Comment by swertz** [comment]
All right I've updated it. I've added the variable `extra_branches` which is a list of strings containing branches the you want to use in the included code, but which are not part of any plot's variable, cut or weight.

**Comment by blinkseb** [comment]
Very nice, thanks :+1:

**Pull request merged**
